In [2]:
import pandas as pd
import json
import os

# Load the datasets
supplierss_df = pd.read_csv('../data/suppliers.csv')

supplierss_df.head()

,supplier_id,supplier_name,category_l1,category_l2,country_hq,service_regions,currency,pricing_model,quality_score,risk_score,esg_score,preferred_supplier,is_restricted,restriction_reason,contract_status,data_residency_supported,capacity_per_month,notes
0,SUP-0001,Dell Enterprise Europe,IT,Laptops,DE,DE;FR;NL;BE;AT;CH;IT;ES;PL,EUR,tiered,87,16,73,True,False,NaN,active,False,18000,NaN
1,SUP-0001,Dell Enterprise Europe,IT,Mobile Workstations,DE,DE;FR;NL;BE;AT;CH;IT;ES;PL,EUR,tiered,85,15,75,True,False,NaN,active,True,18000,NaN
2,SUP-0001,Dell Enterprise Europe,IT,Monitors,DE,DE;FR;NL;BE;AT;CH;IT;ES;PL,EUR,tiered,87,14,75,True,False,NaN,active,True,18000,NaN
3,SUP-0001,Dell Enterprise Europe,IT,Docking Stations,DE,DE;FR;NL;BE;AT;CH;IT;ES;PL,EUR,tiered,85,15,73,True,False,NaN,active,True,18000,NaN
4,SUP-0001,Dell Enterprise Europe,IT,Replacement / Break-Fix Pool Devices,DE,DE;FR;NL;BE;AT;CH;IT;ES;PL,EUR,tiered,85,17,68,True,False,NaN,active,False,18000,NaN

In [3]:
supplierss_df[supplierss_df['is_restricted']]['restriction_reason']

28    Restricted for selected categories and countri...
29    Restricted for selected categories and countri...
Name: restriction_reason, dtype: object

In [ ]:
suppliers_agmanted = pd.read_csv('../data/merged.csv')

suppliers_agmanted.head()

,supplier_id,supplier_name,country_hq,service_regions,pricing_model,capacity_per_month,quality_score,risk_score,esg_score,category_l1,...,is_preferred,is_restricted_global,is_restricted_countries,is_restricted_above_value,restriction_currency,restriction_reason,requires_security_review,requires_cv_review,requires_brand_safety,requires_engineering_so
0,SUP-0001,Dell Enterprise Europe,DE,DE;FR;NL;BE;AT;CH;IT;ES;PL,tiered,18000,85,17,68,IT,...,True,False,NaN,NaN,NaN,NaN,False,False,False,False
1,SUP-0001,Dell Enterprise Europe,DE,DE;FR;NL;BE;AT;CH;IT;ES;PL,tiered,18000,85,17,68,IT,...,True,False,NaN,NaN,NaN,NaN,False,False,False,False
2,SUP-0001,Dell Enterprise Europe,DE,DE;FR;NL;BE;AT;CH;IT;ES;PL,tiered,18000,85,17,68,IT,...,True,False,NaN,NaN,NaN,NaN,False,False,False,False
3,SUP-0001,Dell Enterprise Europe,DE,DE;FR;NL;BE;AT;CH;IT;ES;PL,tiered,18000,85,17,68,IT,...,True,False,NaN,NaN,NaN,NaN,False,False,False,False
4,SUP-0001,Dell Enterprise Europe,DE,DE;FR;NL;BE;AT;CH;IT;ES;PL,tiered,18000,85,17,68,IT,...,True,False,NaN,NaN,NaN,NaN,False,False,False,True